FROM node:24-alpine3.21 AS react-dev

WORKDIR /app

# Set the environment variable to ensure non-interactive install
ENV DEBIAN_FRONTEND=noninteractive

COPY package*.json ./

RUN npm ci

EXPOSE 3000

CMD ["npx", "vite", "--host", "0.0.0.0"]
