name: Tests Workflow

on:
    pull_request:
        branches:
            - main
            - dev
jobs:
    cypress_test:
        runs-on: ubuntu-latest
        steps:
            - name: Set compose file
              id: set-compose
              run: |
                  if [ "${{ github.base_ref }}" = "main" ]; then
                    echo "file=compose.yml" >> $GITHUB_OUTPUT
                  else
                    echo "file=compose-dev.yml" >> $GITHUB_OUTPUT
                  fi

            - name: Build and run tests
              run: docker compose -f ${{ steps.set-compose.outputs.file }} up --build --exit-code-from cypress-test

            - name: Clean container
              if: always()
              run: docker compose -f ${{ steps.set-compose.outputs.file }} down
