name: Tests Workflow

on:
    pull_request:
        branches:
            - main
            - dev

jobs:
    cypress_test:
        if: github.head_ref != 'devops'
        runs-on: ubuntu-latest
        container:
            image: cypress/included:13.13.0

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
<<<<<<< HEAD

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and run tests
              run: docker compose -f compose-dev.yml up --build --exit-code-from cypress-test

            - name: Clean container
              if: always()
              run: docker compose -f compose-dev.yml down
=======
            - name: Setup Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm ci
            - name: Start development server, and testing
              run: npm run dev & sleep 5 && npm test
>>>>>>> dev
